// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// profileConvolution
NumericVector profileConvolution(NumericVector x, NumericVector y, int LS, int US);
RcppExport SEXP profileScoreDist_profileConvolution(SEXP xSEXP, SEXP ySEXP, SEXP LSSEXP, SEXP USSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type LS(LSSEXP);
    Rcpp::traits::input_parameter< int >::type US(USSEXP);
    __result = Rcpp::wrap(profileConvolution(x, y, LS, US));
    return __result;
END_RCPP
}
// profilePosscoreprob
NumericVector profilePosscoreprob(IntegerVector Scores, IntegerVector Srow, NumericVector prow);
RcppExport SEXP profileScoreDist_profilePosscoreprob(SEXP ScoresSEXP, SEXP SrowSEXP, SEXP prowSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type Scores(ScoresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Srow(SrowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prow(prowSEXP);
    __result = Rcpp::wrap(profilePosscoreprob(Scores, Srow, prow));
    return __result;
END_RCPP
}
