# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

profileConvolution <- function(x, y, LS, US) {
    .Call('profileScoreDist_profileConvolution', PACKAGE = 'profileScoreDist', x, y, LS, US)
}

profilePosscoreprob <- function(Scores, Srow, prow) {
    .Call('profileScoreDist_profilePosscoreprob', PACKAGE = 'profileScoreDist', Scores, Srow, prow)
}

